### ISSUE TITLE
Normal ore beneath naturally generated objects

### ISSUE THREAD

**Issue by NenoEntter** [Agzam4/Mindustry-new-game-mode#1]
So, when map generates, some ores are covered with this objects (boulders? dust pile? idk how to call it), and when i deconstruct them, ores are reveal's to be the normal version of themselves (instead sand) allowing temporally mine them.
![Screenshot_1](https://github.com/Agzam4/Mindustry-new-game-mode/assets/154575371/5be62ed3-bd85-41a0-a6c5-844057c8f7c5)
![Screenshot_2](https://github.com/Agzam4/Mindustry-new-game-mode/assets/154575371/cdce2c8e-688a-4858-9664-5e74bd23732b)
![Screenshot_3](https://github.com/Agzam4/Mindustry-new-game-mode/assets/154575371/63144d80-efce-4d0f-baf5-ad2ab6419ae7)
Temporally, because after reloading game - ore goes to sand version as it should be.

**Comment by Agzam4** [comment]
Thanks, fixed in `v1.1.2`
